# Introduction

This is a step-by-step guide to the **openSIMD** R code, which creates the Scottish Index of Multiple Deprivation (SIMD), starting from the indicators.

SIMD is made up of over 30 indicators which are grouped into seven domains of deprivation. Each domain summarises one aspect of deprivation by combining some of the indicators and using the resulting domain scores to rank each area in Scotland. The seven domain rankings are then combined into an overall, multiple-deprivation SIMD ranking.

To run the **openSIMD** R code, you need two datasets, SIMD indicator data, and SIMD domain rankings. Both datasets are included here, but can also be downloaded from the [SIMD website](www.gov.scot/SIMD).

For four out of the seven domains, you will use the SIMD indicator data. For the remaining three domains, you will use the domain rankings instead. The reason for this is that in these three domains, the individual indicators are not made publicly available to ensure that any individual's privacy is protected. For the same reason, the published domain scores are rounded. The domain rankings on the other hand were calculated using unrounded data and are therefore more precise. 

After running the **openSIMD** R code, you will have created two csv documents which contain the domain rankings and the overall SIMD ranking for each small area (called data zone) in Scotland. 

We tested this code with SIMD16 data, and you will need to adapt it for other versions of SIMD. 

The rankings you get when using the **openSIMD** code with the published SIMD16 data slightly differ from the published, offical SIMD16 rankings, see my note in the [Preface](#preface). The overall SIMD rankings differ by up to 18 ranks. More detail about this can be found in the [Quality Assurance](#QA) section. SIMD16 as published on the [SIMD website](www.gov.scot/SIMD) is the official version.

We will now walk you through the R code. In the [Calculating Domains](#calculating-domains) section, we will explain the code used to calculate the individual domain scores. In the section on [Calculating SIMD](#calculating-SIMD), we will go through the steps necessary for combining the domains into the overall SIMD. In the [Functions](#functions) section, we will introduce the **openSIMD** utility functions used throughout the code for those calculation steps that came up repeatedly. And finally, we'll show how well the R code replicates the SAS code in the [Quality Assurance](#QA) section.

For any questions about the SIMD methodology have a look at the SIMD Technical Notes on the [SIMD website](www.gov.scot/SIMD), and feel free to contact the SIMD team at [simd@gov.scot](mailto:simd@gov.scot).
